---
stages:
- name: BUILD 
  inputs:
  - service: ${REPO}
    type: git
    branch: initial-cf
  triggers:
  - type: commit
  jobs:
  - name: Build Catalog Microservice jar file
    type: builder
    artifact_dir: ''
    build_type: gradle
    script: |-
      #!/bin/bash
      # The default Gradle version is {0}
      # To use Gradle {0}, uncomment the following line:
      #export PATH="$GRADLE2_HOME/bin:$PATH"
      export JAVA_HOME=$JAVA8_HOME
      gradle build -x test
- name: DEPLOY
  inputs:
  - type: job
    stage: DEPLOY
    job: Deploy Catalog Microservice application to IBM Cloud
  triggers:
  - type: stage
  properties:
  - name: APP_NAME
    value: 'lightblue-catalog-${SUFFIX}'
    type: text
  jobs:
  - name: Deploy Catalog Microservice
    type: deployer
    deploy_permission: DEV_IN_SPACE
    target:
      region_id: ibm:yp:us-south
      organization: ${ORG}
      space: ${SPACE}
    PORT: ${PORT}
    SUFFIX: ${SUFFIX}
    COMMAND: |-
        #!/bin/sh
        cf push ${APP_NAME} -n ${APP_NAME}
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish

