---
stages:
- name: BUILD 
  inputs:
  - service: ${REPO}
    type: git
    branch: ${BRANCH}
  triggers:
  - type: commit
  jobs:
  - name: Build and Register Catalog Microservice Image
    type: builder
    artifact_dir: ''
    build_type: gradle
    script: |-
      #!/bin/bash
      # The default Gradle version is {0}
      # To use Gradle {0}, uncomment the following line:
      #export PATH="$GRADLE2_HOME/bin:$PATH"
      gradle build -x test
      cp build/libs/*.jar $ARCHIVE_DIR
      cp manifest.yml $ARCHIVE_DIR
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build and Register Catalog Microservice Image
  triggers:
  - type: stage
  properties:
  - name: APP_NAME
    value: 'lightblue-catalog-${SUFFIX}'
    type: text
  jobs:
  - name: Deploy Catalog Microservice
    type: deployer
    deploy_permission: DEV_IN_SPACE
    extension_id: ibm.devops.services.pipeline.docker.deploy.ice
    target:
      region_id: ibm:yp:us-south
      organization: ${ORG}
      space: ${SPACE}
    PORT: ${PORT}
    COMMAND: |-
        #!/bin/sh

        bx app push ${app_name} -n ${app_name}
