---
stages:
- name: BUILD
  inputs:
  - service: ${REPO}
    type: git
    branch: initial-cf
  triggers:
  - type: commit
  jobs:
  - name: Gradle build application
    type: builder
    build_type: gradle
    script: |-
      #!/bin/bash
      # The default Gradle version is {0}
      # To use Gradle {0}, uncomment the following line:
      #export PATH="$GRADLE2_HOME/bin:$PATH"
      export JAVA_HOME=$JAVA8_HOME
      gradle build -x test
- name: DEPLOY
  inputs:
  - type: job
    stage: DEPLOY
    job: Deploy Customer Microservice application to IBM Cloud
  properties:
  - name: SUFFIX
    value: ${SUFFIX}
    type: text
  - name: APP_NAME
    value: lightblue-customer-${SUFFIX}
    type: text
  triggers:
  - type: stage
  jobs:
  - name: Deploy Customer Microservice
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: ${ORG}
      space: ${SPACE}
      application: ${APP_NAME}
    PORT: ${PORT}
    SUFFIX: ${SUFFIX}
    script: |-
        #!/bin/bash
        cf push $APP_NAME -n $APP_NAME
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish

